Clean up using shfmt & other formatters
Visual Studio Code does it automatically. Let’s not fight.

diff --git a/lib/npm b/lib/npm
--- a/lib/npm
+++ b/lib/npm
@@ -3,12 +3,12 @@
 source ./utils
 
 run_npm() {
-    # Check for npm
-    if type_exists 'npm'; then
-        e_header "Installing Node.js packages..."
+	# Check for npm
+	if type_exists 'npm'; then
+		e_header "Installing Node.js packages..."
 
-        # List of npm packages
-        local packages="
+		# List of npm packages
+		local packages="
                         alex
                         alfred-polyglot-fork
                         alfred-show-network-info
@@ -33,16 +33,16 @@ run_npm() {
                         yo
         "
 
-        # Install packages globally and quietly
-        npm install $packages --global --quiet
+		# Install packages globally and quietly
+		npm install $packages --global --quiet
 
-        [[ $? ]] && e_success "Done"
-    else
-        printf "\n"
-        e_error "Error: npm not found."
-        printf "Aborting...\n"
-        exit
-    fi
+		[[ $? ]] && e_success "Done"
+	else
+		printf "\n"
+		e_error "Error: npm not found."
+		printf "Aborting...\n"
+		exit
+	fi
 }
 # Install Node packages
 run_npm
